### ISSUE TITLE
Website out of service

### ISSUE THREAD

**Issue by flaviolenz** [tlstyer/acquire#8]
Is the website out?

**Comment by dpebert7** [comment]
It's working fine for me at the moment.

**Comment by flaviolenz** [comment]
It's back now.
But it was more than 24h unavailable.

Em qui, 26 de nov de 2020 05:30, David E <notifications@github.com>
escreveu:

**Comment by tlstyer** [comment]
It was out. My hosting provider at the time was having lots of issues. I changed hosting providers. Now it's working again.
